services:
  tsmlwp:
    depends_on:
      - tsmldb
    build:
      dockerfile: ./dockerfile
      context: .
    ports:
      - ${WP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: tsmldb:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      XDEBUG_MODE: debug
    volumes:
      - ./wproot/:/var/www/html
      - ./files:/var/www/html/files
      - ./plugins/12-step-meeting-list:/var/www/html/wp-content/plugins/12-step-meeting-list
      - ./plugins/tsml-test:/var/www/html/wp-content/plugins/tsml-test
  tsmldb:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - tsml_mysql:/var/lib/mysql

  wpcli:
    depends_on:
      - tsmlwp
      - tsmldb
    image: wordpress:cli
    user: '33'
    volumes:
      - ./wproot/:/var/www/html
    environment:
      WP_CLI_CACHE_DIR: ${WP_CLI_CACHE_DIR}
      WORDPRESS_DB_HOST: tsmldb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    command: >
      /bin/sh -c '
      echo "Waiting for MySQL to be ready...";
      sleep 10;
      wp core install --path=/var/www/html --url=http://${WP_HOST}:${WP_PORT} --title="${WP_BLOG_NAME}" --admin_user=${WP_ADMIN_USER} --admin_password=${WP_ADMIN_PASSWORD} --admin_email=${WP_ADMIN_EMAIL};
      sleep 5;
      wp plugin activate 12-step-meeting-list --network --path=/var/www/html;
      wp option update blog_public 0 --path=/var/www/html;
      wp option update siteurl http://${WP_HOST}:${WP_PORT} --path=/var/www/html;
      wp option update home http://${WP_HOST}:${WP_PORT} --path=/var/www/html;
      wp rewrite structure '/%year%/%monthnum%/%postname%/' --path=/var/www/html;
      wp rewrite flush --path=/var/www/html;
      wp cache flush --path=/var/www/html;
      '

volumes:
  tsml_mysql: